# https://hub.docker.com/r/teddysun/v2ray
name: v2ray

services:
  v2ray:
    restart: always
    container_name: v2ray
    image: teddysun/v2ray
    ports:
      - 10808:10808
    volumes:
      - v2ray:/etc/v2ray:/etc/v2ray

volumes:
  v2ray:
    external: true
